package org.talend.designer.codegen.translators.internet.scp;

import org.talend.core.model.process.INode;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.designer.codegen.config.CodeGeneratorArgument;

public class TSCPFileExistsMainJava
{
  protected static String nl;
  public static synchronized TSCPFileExistsMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TSCPFileExistsMainJava result = new TSCPFileExistsMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "\t\t" + NL + "\t\t//initial the command" + NL + "\t\tStringBuilder command_";
  protected final String TEXT_2 = " = new StringBuilder();" + NL + "\t\t" + NL + "\t\tfinal String dir_";
  protected final String TEXT_3 = " = String.valueOf(";
  protected final String TEXT_4 = ");" + NL + "\t\tfinal String file_";
  protected final String TEXT_5 = " = String.valueOf(";
  protected final String TEXT_6 = ");" + NL + "\t\t" + NL + "\t\tcommand_";
  protected final String TEXT_7 = ".append(\"ls \");" + NL + "\t\t" + NL + "\t\tif(dir_";
  protected final String TEXT_8 = ".contains(\"*\") || dir_";
  protected final String TEXT_9 = ".contains(\"?\") || dir_";
  protected final String TEXT_10 = ".contains(\"[\") || dir_";
  protected final String TEXT_11 = ".contains(\"]\")) {" + NL + "\t\t\t\tcommand_";
  protected final String TEXT_12 = ".append(dir_";
  protected final String TEXT_13 = ");" + NL + "        } else {" + NL + "        \t\tcommand_";
  protected final String TEXT_14 = ".append(\"\\\"\").append(dir_";
  protected final String TEXT_15 = ").append(\"\\\"\");" + NL + "        }" + NL + "        " + NL + "        command_";
  protected final String TEXT_16 = ".append(\"/\");" + NL + "        " + NL + "      \tif(file_";
  protected final String TEXT_17 = ".contains(\"*\") || file_";
  protected final String TEXT_18 = ".contains(\"?\") || file_";
  protected final String TEXT_19 = ".contains(\"[\") || file_";
  protected final String TEXT_20 = ".contains(\"]\")) {" + NL + "\t\t\t\tcommand_";
  protected final String TEXT_21 = ".append(file_";
  protected final String TEXT_22 = ");" + NL + "        } else {" + NL + "        \t\tcommand_";
  protected final String TEXT_23 = ".append(\"\\\"\").append(file_";
  protected final String TEXT_24 = ").append(\"\\\"\");" + NL + "        }" + NL + "    " + NL + "\t\tglobalMap.put(\"";
  protected final String TEXT_25 = "_FILENAME\", ";
  protected final String TEXT_26 = ");" + NL + "\t\t/* Create a session */" + NL + "\t\tch.ethz.ssh2.Session sess_";
  protected final String TEXT_27 = " = conn_";
  protected final String TEXT_28 = ".openSession();" + NL + "\t\t//execute the command" + NL + "\t\tsess_";
  protected final String TEXT_29 = ".execCommand((command_";
  protected final String TEXT_30 = ").toString());" + NL + "\t\t" + NL + "\t\t//get the return info" + NL + "\t\tjava.io.InputStream stdout_";
  protected final String TEXT_31 = " = sess_";
  protected final String TEXT_32 = ".getStdout();" + NL + "\t\tjava.io.BufferedReader brout_";
  protected final String TEXT_33 = "= new java.io.BufferedReader(new java.io.InputStreamReader(stdout_";
  protected final String TEXT_34 = "));" + NL + "        String line_out_";
  protected final String TEXT_35 = " = \"\";" + NL + "        StringBuilder stringStdout_";
  protected final String TEXT_36 = " =new StringBuilder();" + NL + "\t\twhile((line_out_";
  protected final String TEXT_37 = " = brout_";
  protected final String TEXT_38 = ".readLine()) != null) {" + NL + "\t\t\tstringStdout_";
  protected final String TEXT_39 = ".append(line_out_";
  protected final String TEXT_40 = " + \"\\n\");" + NL + "\t\t}\t\t" + NL + "\t    brout_";
  protected final String TEXT_41 = ".close();" + NL + "\t\tstdout_";
  protected final String TEXT_42 = ".close();" + NL + "\t\tjava.io.InputStream stderr_";
  protected final String TEXT_43 = " = sess_";
  protected final String TEXT_44 = ".getStderr();" + NL + "        java.io.BufferedReader breer_";
  protected final String TEXT_45 = "= new java.io.BufferedReader(new java.io.InputStreamReader(stderr_";
  protected final String TEXT_46 = "));" + NL + "        String line_err_";
  protected final String TEXT_47 = " = \"\";" + NL + "        StringBuilder stringStderr_";
  protected final String TEXT_48 = " =new StringBuilder();" + NL + "\t\twhile((line_err_";
  protected final String TEXT_49 = " = breer_";
  protected final String TEXT_50 = ".readLine()) != null) {" + NL + "\t\t\tstringStderr_";
  protected final String TEXT_51 = ".append(line_err_";
  protected final String TEXT_52 = " + \"\\n\");" + NL + "\t\t}" + NL + "\t\tbreer_";
  protected final String TEXT_53 = ".close();" + NL + "\t\tstderr_";
  protected final String TEXT_54 = ".close();" + NL + "\t\t /* Close this session */\t\t\t" + NL + "\t\tsess_";
  protected final String TEXT_55 = ".close();" + NL + "\t\tif((\"\").equals(stringStderr_";
  protected final String TEXT_56 = ".toString()) || stringStderr_";
  protected final String TEXT_57 = ".toString() == null){" + NL + "\t\t\t";
  protected final String TEXT_58 = NL + "\t\t\t\tlog.debug(\"";
  protected final String TEXT_59 = " - The file '\" + ";
  protected final String TEXT_60 = " + \"' exists in the remote directory '\"+ ";
  protected final String TEXT_61 = " + \"'.\");" + NL + "\t\t\t";
  protected final String TEXT_62 = NL + "\t\t\tglobalMap.put(\"";
  protected final String TEXT_63 = "_STATUS\", \"File exists.\");" + NL + "\t\t}else{" + NL + "\t\t\t";
  protected final String TEXT_64 = NL + "\t\t\t\tlog.debug(\"";
  protected final String TEXT_65 = " - The file '\" + ";
  protected final String TEXT_66 = " + \"' doesn't exist in the remote directory '\"+ ";
  protected final String TEXT_67 = " + \"'.\");" + NL + "\t\t\t";
  protected final String TEXT_68 = NL + "        \tglobalMap.put(\"";
  protected final String TEXT_69 = "_STATUS\", stringStderr_";
  protected final String TEXT_70 = ".toString());" + NL + "        }";
  protected final String TEXT_71 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    
    CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
    INode node = (INode)codeGenArgument.getArgument();
    String cid = node.getUniqueName();
    String remoteDir = ElementParameterParser.getValue(node,"__REMOTEDIR__");
    String fileExists = ElementParameterParser.getValue(node,"__EXISTFILE__");
    boolean isLog4jEnabled = ("true").equals(ElementParameterParser.getValue(node.getProcess(), "__LOG4J_ACTIVATE__"));

    stringBuffer.append(TEXT_1);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_2);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(remoteDir );
    stringBuffer.append(TEXT_4);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_5);
    stringBuffer.append(fileExists );
    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_25);
    stringBuffer.append(fileExists );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_57);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_59);
    stringBuffer.append(fileExists );
    stringBuffer.append(TEXT_60);
    stringBuffer.append(remoteDir );
    stringBuffer.append(TEXT_61);
    }
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_63);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_65);
    stringBuffer.append(fileExists );
    stringBuffer.append(TEXT_66);
    stringBuffer.append(remoteDir );
    stringBuffer.append(TEXT_67);
    }
    stringBuffer.append(TEXT_68);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_70);
    stringBuffer.append(TEXT_71);
    return stringBuffer.toString();
  }
}
